---
version: 0.2
env: 
  variables:
    BACKEND_URL:
phases: 
  install:
    runtime-versions:
      nodejs: 18
    commands: 
      - echo "insalling tools"
      - npm --v
      - node -v
  pre_build:
    commands: 
      - echo "installing dependencies"
      - npm install
      - sed -i "s|BACKEND_URL|$BACKEND_URL|g" src/environments/environment.prod.ts
  build:
    commands:
      - npm run build

artifacts: 
  files: 
    - "**/*"
  base-directory: dist/frontend/browser